include:
    - project: cm-tm/cm-team/pipelineartifacts/pipeline
      ref: "1"
      file : base.yaml
    - project: cm-tm/cm-team/pipelineartifacts/pipeline
      ref: "1"
      file : image.yaml
    - project: cm-tm/cm-team/pipelineartifacts/pipeline
      ref: "1"
      file : chart.yaml
    - project: cm-tm/cm-team/pipelineartifacts/pipeline
      ref: "1"
      file : deploy.yaml
    - project: cm-tm/cm-team/pipelineartifacts/pipeline
      ref: "1"
      file : maven.yaml
    - local: 'variables.yaml'
    
chart:
  image: iai-artifactory.iai.kit.edu/docker-cm/iai-pipeline:2387477a
