apiVersion: v1
kind: Service
metadata:
  name: {{ include "sensingdevice.fullname" . }}
  labels:
    {{- include "sensingdevice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.monitoring.enabled }}
    - port: 9901
      targetPort: 9901
      protocol: TCP
      name: prometheus
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    {{ else }}
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
  selector:
    {{- include "sensingdevice.selectorLabels" . | nindent 4 }}
